server:
    port: 8888
spring:
    cloud:
        config:
            server:
                encrypt:
                    enabled: false
                git:
                    uri: https://github.com/johndcx45/bookstore-config-server
                    search-paths: management, stock
                    default-label: main
